name: Docker Image CI

on: [push]
env:
  DOCKER_IMAGE_NAME: sitapati/camunda-cloud-demo-json-api

jobs:
  publish_docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker image to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ env.DOCKER_IMAGE_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tags: 'latest'
